name: Build and Push Docker Image

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            creowave/postgres
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Load build args from .env
        id: env
        run: |
          set -a
          source .env
          set +a
          echo "base_image=$BASE_IMAGE" >> $GITHUB_OUTPUT
          echo "postgis_version=$POSTGIS_VERSION" >> $GITHUB_OUTPUT
          echo "postgis_sha256=$POSTGIS_SHA256" >> $GITHUB_OUTPUT
          echo "timescaledb_version=$TIMESCALEDB_VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ steps.env.outputs.base_image }}
            POSTGIS_VERSION=${{ steps.env.outputs.postgis_version }}
            POSTGIS_SHA256=${{ steps.env.outputs.postgis_sha256 }}
            TIMESCALEDB_VERSION=${{ steps.env.outputs.timescaledb_version }}
